export enum Environment {
  MONGO_ATLAS = 'MONGO_ATLAS',
  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',
  SERVER_PORT = 'SERVER_PORT',
  BYPASS_PLAY = 'BYPASS_PLAY',
}

export enum Microservice {
  MESSAGE_BROKER = 'MESSAGE_BROKER',
}
